name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20.x

      # - name: Install dependencies
      #   run: npm ci

      # - name: Get Project Version
      #   id: get_version
      #   run: echo ::set-output name=version::$(node -p "require('./package.json').version")

      # - name: Build application for Windows
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #   run: npm run make:win

      # - name: Publish application
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #   run: npm run publish

      - name: Check if the file exists
        id: check-file
        run: test -f "D:/a/electronX/electronX/out/make"

      - name: Upload builds to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.10
          files: "D:/a/electronX/electronX/out/make/squirrel.windows/x64/Xecta App-0.0.10 Setup.exe"
          draft: true
          repository: "XectaDigitalLab/Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
