name: List Folders and Subfolders

on:
  push:
    branches:
      - main

jobs:
  list-folders:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Folders and Subfolders
        run: |
          dir D:\a\electronX\electronX\out\make /s /b /ad
