name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  configure-git:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git user and bump version
        run: |
          git config --global user.email "suyashpandey152@gmail.com"
          git config --global user.name "usersuyashpandey"
          npm version patch -m "Automatic version bump to %s [skip ci]"
          git push origin HEAD:main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Print package version
        run: echo : $(node -p \"require('./package.json').version\")

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
      discussions: write
    needs: configure-git

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build Electron app for Windows
        run: npm run make:win

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            D:/a/electronX/electronX/out/make/squirrel.windows/x64/*.exe
          tag_name: v${{ needs.configure-git.outputs.package.version }}

  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
      discussions: write
    needs: configure-git

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install setuptools
        run: |
          python3 -m pip install setuptools
          npm ci

      - name: Install dependencies
        run: npm install

      - name: Build Electron app for macOS
        run: npm run make:mac

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            /Users/runner/work/electronX/electronX/out/make/*.dmg
          tag_name: v${{ needs.configure-git.outputs.package.version }}
          overwrite: true
