name: Check C Drive Folder Structure

on:
  push:
    branches:
      - main

jobs:
  check-c-drive:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check C Drive Folder Structure
        run: |
          # Print the folder structure of the C drive using PowerShell
          Get-ChildItem 'C:\' -Recurse | Where-Object { $_.PSIsContainer } | Format-Table

    # Add more steps or actions as needed for your workflow
