name: Find EXE Artifact

on:
  push:
    branches:
      - main

jobs:
  find-exe-artifact:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find EXE Artifact
        run: |
          # Debugging: Print the contents of the directory
          Get-ChildItem -Recurse | Format-Table

            # Search for the 'out' directory under the specified path using PowerShell
            $outDirectory = Get-ChildItem -Recurse -Path 'D:\a\electronX\electronX' -Filter 'out' | Where-Object { $_.PSIsContainer -and $_.Name -eq 'out' } | Select-Object -ExpandProperty FullName

            if ($exeArtifact -ne $null) {
              Write-Host "Found EXE artifact at: $exeArtifact"
            } else {
              Write-Host "Could not find EXE artifact."
            }
          } else {
            Write-Host "Directory $outDirectory does not exist."
          }

    # Add more steps or actions as needed for your workflow
