name: Find .exe File

on:
  push:
    branches:
      - main

jobs:
  find-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find .exe File
        run: |
          # Search for the .exe file using PowerShell
          $exePath = Get-ChildItem -Recurse -Filter 'Xecta-App-0.0.3-Setup.exe' | Select-Object -ExpandProperty FullName

          if ($exePath -ne $null) {
            Write-Host "Found .exe file at: $exePath"
          } else {
            Write-Host "Could not find the .exe file."
          }

    # Add more steps or actions as needed for your workflow
