name: Find .exe File

on:
  push:
    branches:
      - main

jobs:
  find-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print directory structure
        uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
