name: Find .exe File

on:
  push:
    branches:
      - main

jobs:
  find-out-directory:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print directory structure
        run: |
          echo "Directory structure:"
          ls -R
