name: Find Out Directory

on:
  push:
    branches:
      - main

jobs:
  find-out-directory:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find Out Directory
        run: |
          # Debugging: Print the contents of the directory
          Get-ChildItem -Recurse | Format-Table

          # Search for the 'out' directory under the specified path using PowerShell
          $outDirectory = Get-ChildItem -Recurse -Path 'Directory: D:\a\electronX\electronX' -Filter 'out' | Where-Object { $_.PSIsContainer -and $_.Name -eq 'out' } | Select-Object -ExpandProperty FullName

          if ($outDirectory -ne $null) {
            Write-Host "Found 'out' directory at: $outDirectory"
          } else {
            Write-Host "Could not find 'out' directory."
          }

    # Add more steps or actions as needed for your workflow
