name: Find Xecta-App-Setup.exe

on:
  push:
    branches:
      - main

jobs:
  find-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find Xecta-App-Setup.exe
        run: |
          # Search for the Xecta-App-Setup.exe file using PowerShell with a wildcard
          $exePath = Get-ChildItem -Recurse -Filter 'Xecta-App-*-Setup.exe' | Select-Object -ExpandProperty FullName

          if ($exePath -ne $null) {
            Write-Host "Found Xecta-App-Setup.exe at: $exePath"
          } else {
            Write-Host "Could not find Xecta-App-Setup.exe."
          }

    # Add more steps or actions as needed for your workflow
